name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_app_executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install -r hf_upload_app/requirements.txt
      - name: Build with PyInstaller
        run: |
          python -m pip install pyinstaller
          cd hf_upload_app
          pyinstaller hf_upload_app.spec --noconfirm
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: |
            hf_upload_app/dist/hf-uploader-app
            hf_upload_app/dist/hf-uploader-app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
